services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: "development"
      DATABASE_HOST: "db"
      DATABASE_USER: "postgres"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres-data:
